language: node_js
node_js:
  - stable
cache: yarn
script:
  - gulp build --production
  - tar cvzf dist.tgz dist/*
deploy:
  provider: releases
  api_key:
    secure: GI/9BNEHRGa2cenU+XQRp6muw2r4TxG3XRlB15Bb27OzF30MhSWk9B8GHFfgnIJWe4E+bI2O9YFxE3McmiwJoxQTIqWwuiaq/tWrETlMKBi/GKiEX8ppUC2VtCbDOb17lYinVDfCX0mAIz04HVz6YqyE5rQj1RNRz6RzbFcBL9gyn1/eXsnKf83A1ON6VsNJMEkYiAmU103jGMPSzdNb//gSUKSL1+20on3jSrC0Q0HlwHcyAht12Iot6/ed2QOEKChhOzcWoyOaamuGew1LoCEhfYnx5Z+kFzGpvu91aQuNzAVlbgnpyhhQP59IJDqJy/9FHl9EmLxyvcVcbgZTxXMnHUOWoc9izL5eSVwUZbv6HST+y5y1L9tiKVB1Ja8FiOtPi1hQ1q/rDnHVRsQWIAnPEHEFOZ2Chz8LumEwJEZpyEcIGeGM0wsdhXx0X55aVN0kmrKrJS1djjGme1FvAeKFoyOwEVRnx1hHiQuEfrXr9CIo0GONND2VwaxHHn5DRM5f39hn9uYL+IbrWH+cVpyIkkQUfCYZZME6qVEjEvkoHDhax7YeNgs+nkvtc1x6I1ZQAMtwqyJE01+16z1Qjq+vjUoHbyjOQUUgjOulVKmmCvmRcfLFYbfAVHDfyw+QCLmoOFBsCz+hL8A/XaFc6eaouE3IKfPPyg5vRcoZwC8=
  file: dist.tgz
  skip_cleanup: true
  on:
    repo: Dramloc/angular-material-boilerplate
