language: node_js
node_js:
- stable
script: gulp build --production
deploy:
  provider: heroku
  api_key:
    secure: uqZlMrMF5iyODYmKD1UgYl1G55Ct/nGxJf7hXNoyntQRvh1493Icp0xfH5CK97swjJ1O2WDkx5TKKTOGEummjPQMwKU8C7VDkkDXnCuTw9hXVBt+E390xvI3l17tlIgCsqKNQ0jNae3YkZXbdQbOIuq7+0QSM0lYl1nIR/e6gEcbsBWZ0gV7sdbz+WraD3Y9RzyKPc6urthqcfqB7SMXEEPKs3ahgdlriFoAdDwPI7wfSa9hLpwxTZa7R6whDmqitrqgJJ37MX8TELQdwverlYjznvUsC+GBUQAnRmfYbgz/fjD9Viueg5vgAKkjplWoeE2XxUwwEwRahW8CTnn4QCF5SVpT7WvBos1Jj9ocGcjFGh8CDxYadaM0tBrbGSdmexQ+Jp8fdi6sVG7JqTvL4dAU4/R1xGiE21N0YRpbR2zo90gU2ArGcYVZc/qEPJLq7l2OcQM3MTU2VWjpN/MZwuk7l28Y8VcDd3GuvnyhbVI7/vWHyH17/Exmf+fPZtigC7zKSAsT4VrcPIRW8WdEGA2zHdJ1rIs42HLfO0jzcO+A3Ha35HHROcB+1Gl0hpyer59R1FSh9wx3N6cZcEV1P4EchvpJeENmwkQBY5DjhPg3I1aiKlq546q1YYnEqxWdKo8YaGZAY8w9vmYbYs5IeYFWJTDD/PDsFjYwR9CGXVo=
  app: angular-material-boilerplate
  on:
    repo: Dramloc/angular-material-boilerplate
