language: node_js
node_js:
- stable
cache: yarn
script:
- gulp build --production
- tar cvzf dist.tgz dist/*
deploy:
  provider: heroku
  api_key:
    secure: n+0xFPDkckXZ1razu7Pvu0ZcA4wJTBHx9JvP9gB5djbuvVFET6BwaA7sUa2WkLHSsxJl4PbzUqhqn2C98ihHWj+i0Ncwbr81ThYprgcGDI5+R8fK9syI96xBjytTtlTAA7AIyx1JKBZ7RL0y15WMK3wq7M0yLHbcrTS0BiCQY3j3WlO7dcIF75E1O1bFOAdT9rGosdW7T4VLfQpJepIa5FZz8zujM85o50mjqt9ZEcnCFAjYCZBRCa/wiSC+cy75XJLvleHTpnctn/pKtlQNJukta5TYz6aaRbaVzHnDPPvik66ptZqMLlF5fqAbQfXhVFHMWDCev6ILxWg5MbZmsPiTJIfdthb+y/zcssNTtZaK80v/af1OkhhQh0GY9z1nXbegno9hiXuOFdd2EXfHrf48PR5+Fb1K5bEe812cvUlZjIhIkODRbEO3IvWXMmtBsbdBB5/yAXRooVxztYU9Id/BNIG4CZF1AIAbC5O6wQoMz/gj1REGOGdl31talhAVPKxisAv+RXoDoIl0dlA81kF07DPJFo/ioiR+U+w1spKxpM5f2Ii/H9XtwHhiNnH/LxjXP1byosqdTiMpp+4SWT+wXdzoRE4cbZV4vNM2HRc3l3DbFvE/ZQRd7QKnSTscRAL7ZzUBTTGgX7VL6SMoe9DZQZ1M2H8tseJKf3HEKcI=
  skip_cleanup: true
  app: angular-material-boilerplate
  on:
    repo: Dramloc/angular-material-boilerplate
